###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_USER: php
      MYSQL_PASSWORD: php
      MYSQL_DATABASE: cursophp
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8001:80

  webserver:
    image: "nginx:alpine"
    working_dir: /app
    volumes:
      - ".:/app"
      - "./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "3333:80"

  php-fpm:
    build: phpdocker/php-fpm
    working_dir: /app
    volumes:
      - ".:/app"
      - "./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini"
